#!/usr/bin/env bash
# shellcheck shell=bash
#
# composes this repo's agent-context-* apm packages into the repo-root
# AGENTS.md, plus a one-line CLAUDE.md pointer. The fragments under
# modules/home/ai/plugins/agent-context-{core,vcs,vcs-jj,vanixiets}/
# .apm/instructions/*.instructions.md are composed two ways: this script
# (apm compile) produces the git-ignored repo-root AGENTS.md, and nix's
# `programs.agents-md` (builtins.readFile) composes the same fragments
# into the eight user-level harness surfaces.
#
# why staging is required, not stylistic: apm's first-party primitive
# discovery is recursive over the project tree but gated on at least one
# fragment existing directly under the project's OWN root .apm/ (the
# "monorepo-hybrid" publisher shape; OpenAPM v0.1 req-tg-007). This
# repo's root carries no .apm/ directory, so a bare `apm compile` at the
# root emits nothing. apm also has no primitive include/exclude filter,
# so tier selection (default vs --full) is achieved only by choosing
# which packages' fragments get copied into a synthetic
# .apm/instructions/ before compiling.
#
# why the compilation: config lives in the root apm.yml, not a staging
# one: `apm compile --root DIR` writes outputs under DIR while resolving
# primitives (.apm/, and apm.yml for project identity) from $PWD -- but
# CompilationConfig.from_apm_yml is not override-aware: it always reads
# the `compilation:` block from apm.yml at the --root target, never from
# $PWD's apm.yml (verified empirically: a source_attribution mismatch
# between a staging apm.yml and the --root apm.yml resolves to the
# --root value). `source_attribution: true` is therefore set on the
# repo-root apm.yml, the target this script always compiles into. Do
# not "simplify" this into reading compilation: config from the staging
# apm.yml; it will silently stop taking effect.
#
# why --target codex is passed explicitly rather than set in apm.yml:
# apm's target resolution for `apm compile` (explicit --target flag >
# apm.yml top-level targets:/target: > auto-detect) is the SAME
# resolution chain `apm install` uses, and it reads the SAME apm.yml
# top-level `targets:` field already set to [agent-skills] for the
# pre-existing skills consumer path (apm-skills-install.sh). A
# `compilation.target` key under the `compilation:` block is parsed by
# CompilationConfig.from_apm_yml but is always overwritten by the CLI's
# already-resolved effective target before the config object is built,
# so setting it in apm.yml has zero effect on actual behavior -- it is
# not configured there. codex is the target whose compile family,
# absent any agent/hook/skill primitives (this repo's context packages
# carry only instructions/), emits exactly one file: the root AGENTS.md.
# Verified empirically that a bogus dependencies.apm entry in the root
# apm.yml is never touched by this compile: dependency/marketplace
# resolution is an `apm install`/`apm pack` concern, not `apm compile`.
#
# default tier selection (vanixiets only) vs --full: on a machine with
# the home-manager profile applied, the user-level context files
# (~/.claude/CLAUDE.md etc, generated by modules/home/tools/agents-md.nix
# from these same fragments) already carry the core/vcs/vcs-jj prose.
# Claude Code loads user-level AND project-level context and
# concatenates them WITHOUT de-duplication, so a project AGENTS.md
# repeating the global tiers would re-inject roughly 4,400-4,900 tokens
# every session. --full composes all four tiers, for a fresh clone or
# ephemeral environment with no user-level context at all.
#
# grep-able marker: APM-CONTEXT-COMPILE-OK
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: apm-context-compile [--full] [-h|--help]

Composes the repo's agent-context-* apm instruction fragments into the
repo-root AGENTS.md, and writes a one-line CLAUDE.md pointer (`@AGENTS.md`).

Replaces the repo-root AGENTS.md / CLAUDE.md symlinks (into the planning
repo's vanixiets.md context) with regular, git-ignored, generated files.
The planning-repo file is left byte-intact.

Modes:
  (default)  vanixiets tier only (this repo's own context fragments).
  --full     core + vcs + vcs-jj + vanixiets (every tier); for a fresh
             clone or ephemeral environment with no user-level context.

Options:
  -h, --help  show this help and exit.
EOF
}

full=0
while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    --full) full=1 ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

# guard: refuse to run against anything but this repository's producer
# manifest, so a misplaced invocation cannot overwrite an unrelated
# project's AGENTS.md / CLAUDE.md.
if [ ! -f apm.yml ]; then
  echo "apm-context-compile: no apm.yml at ${repo_root}" >&2
  exit 1
fi
manifest_output="$(yq -r '.marketplace.output' apm.yml)"
if [ "${manifest_output}" != ".github/plugin/marketplace.json" ]; then
  echo "apm-context-compile: apm.yml at ${repo_root} is not the vanixiets producer manifest (marketplace.output=${manifest_output})" >&2
  exit 1
fi

if [ "${full}" -eq 1 ]; then
  tier_codes=(10 20 30 40)
  tier_pkgs=(agent-context-core agent-context-vcs agent-context-vcs-jj agent-context-vanixiets)
else
  tier_codes=(40)
  tier_pkgs=(agent-context-vanixiets)
fi

echo "=== apm-context-compile (full=${full}) ==="
echo "repo_root: ${repo_root}"
apm --version | head -1 || true
echo "tiers: ${tier_pkgs[*]}"
echo ""

missing=()
plan_codes=()
plan_pkgs=()
plan_srcs=()
fragment_count=0
for i in "${!tier_pkgs[@]}"; do
  pkg="${tier_pkgs[$i]}"
  code="${tier_codes[$i]}"
  instr_dir="${repo_root}/modules/home/ai/plugins/${pkg}/.apm/instructions"
  if [ ! -d "${instr_dir}" ]; then
    missing+=("${instr_dir} (directory does not exist)")
    continue
  fi
  mapfile -t pkg_fragments < <(find "${instr_dir}" -maxdepth 1 -name '*.instructions.md' | sort)
  if [ "${#pkg_fragments[@]}" -eq 0 ]; then
    missing+=("${instr_dir} (no *.instructions.md files)")
    continue
  fi
  for f in "${pkg_fragments[@]}"; do
    plan_codes+=("${code}")
    plan_pkgs+=("${pkg}")
    plan_srcs+=("${f}")
    fragment_count=$((fragment_count + 1))
  done
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "apm-context-compile: missing or empty package instruction directories:" >&2
  for m in "${missing[@]}"; do
    echo "  ${m}" >&2
  done
  echo "apm-context-compile: refusing to compose a partial/empty document; fix the above and rerun." >&2
  exit 1
fi

TMP="$(mktemp -d "${TMPDIR:-/tmp}/apm-context-compile.XXXXXX")"
trap 'rm -rf "${TMP}"' EXIT
mkdir -p "${TMP}/.apm/instructions"
cat >"${TMP}/apm.yml" <<'STAGING_EOF'
name: apm-context-compile-staging
version: 0.0.0
description: Transient staging manifest for apm-context-compile; never committed.
STAGING_EOF

for i in "${!plan_srcs[@]}"; do
  code="${plan_codes[$i]}"
  pkg="${plan_pkgs[$i]}"
  src="${plan_srcs[$i]}"
  base="$(basename "${src}")"
  cp "${src}" "${TMP}/.apm/instructions/${code}-${pkg}--${base}"
done

echo "staged ${fragment_count} fragment(s) from ${#tier_pkgs[@]} tier(s) into ${TMP}/.apm/instructions/"
echo ""

echo "WARNING: ${repo_root}/AGENTS.md and ${repo_root}/CLAUDE.md may still be"
echo "symlinks into the planning repo's vanixiets.md context. This run REPLACES"
echo "both with regular, generated files -- the intended migration. Both paths"
echo "are already git-ignored, and any existing symlink is unlinked before"
echo "writing, so nothing is ever written through a link into another repository."
echo ""

# A shell redirect FOLLOWS a symlink, so writing these paths in place would
# write into the planning repo through the link instead of replacing it. That
# is not hypothetical: it clobbered contexts/vanixiets.md there once. apm
# compile itself is safe because it writes via os.replace, but unlinking both
# up front makes the invariant uniform and independent of that detail.
for generated in AGENTS.md CLAUDE.md; do
  if [ -L "${repo_root}/${generated}" ]; then
    echo "unlinking existing symlink ${repo_root}/${generated} -> $(readlink "${repo_root}/${generated}")"
    rm -f "${repo_root}/${generated}"
  fi
done
echo ""

(
  cd "${TMP}"
  apm compile --root "${repo_root}" --target codex
)

printf '@AGENTS.md\n' >"${repo_root}/CLAUDE.md"

section_count="$(grep -c '^## ' "${repo_root}/AGENTS.md" || true)"

echo ""
echo "paths written:"
echo "  ${repo_root}/AGENTS.md"
echo "  ${repo_root}/CLAUDE.md"
echo "section count (## headings, incl. the synthesized Global Instructions heading): ${section_count}"
echo ""
echo "APM-CONTEXT-COMPILE-OK: ${fragment_count} fragment(s) composed, ${section_count} section(s)"
